import { FinanceiroProvider } from "@/context/financeiroContext";
import { Header } from "@/components";
import "./globals.css";
import { ParceladoProvider } from "@/context/parceladoContext";
import Login from "@/components/Login";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FinanceiroProvider>
          <Login>
            <Header>
              <ParceladoProvider>{children}</ParceladoProvider>
            </Header>
          </Login>
        </FinanceiroProvider>
      </body>
    </html>
  );
}
